name: Test

on:
  push:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |  # Checkout only committed files using Git commands
          git fetch --depth=1 origin $(git rev-parse --abbrev-ref HEAD)
          git checkout $(git rev-parse --abbrev-ref HEAD)
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - uses: ./
